# Generated by Django 5.0 on 2025-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instapay_number', models.CharField(default='01XXXXXXXXX', max_length=20, verbose_name='رقم إنستاباي')),
                ('vodafone_cash_number', models.CharField(default='01XXXXXXXXX', max_length=20, verbose_name='رقم فودافون كاش')),
                ('bank_account_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل الحساب البنكي')),
                ('is_card_enabled', models.BooleanField(default=True, verbose_name='تفعيل الدفع بالبطاقة')),
                ('is_instapay_enabled', models.BooleanField(default=True, verbose_name='تفعيل الدفع بإنستاباي')),
                ('is_vodafone_cash_enabled', models.BooleanField(default=True, verbose_name='تفعيل الدفع بفودافون كاش')),
                ('is_cod_enabled', models.BooleanField(default=True, verbose_name='تفعيل الدفع عند الاستلام')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الدفع',
                'verbose_name_plural': 'إعدادات الدفع',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط إيصال الدفع'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف المرسل'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العملية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني للعميل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='رقم هاتف العميل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تم الدفع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('card', 'بطاقة ائتمانية'), ('instapay', 'إنستاباي'), ('vodafone_cash', 'فودافون كاش')], default='cod', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(verbose_name='عنوان الشحن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي'),
        ),
    ]
