# Generated by Django 5.0 on 2025-05-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_paymentsettings_order_receipt_url_order_sender_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='إيصال الدفع'),
        ),
    ]
